spring:
  application:
    name: Java Training Exercise 4
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:h2:mem:./target/database/data;DB_CLOSE_DELAY=-1
    username: dba
    password: mypassword01
  h2.console.enabled: false
  data.jpa.repositories.bootstrap-mode: default