spring:
  application:
    name: Java Training Exercise 4
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:h2:file:./target/database/data
    username: dba
    password: mypassword01